version: '3.8'

services:
  # Service untuk MySQL
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pmysecretpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service untuk Express.js
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=mydatabase

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy
    environment:
      VITE_API_URL: http://localhost:3000
    healthcheck:
      test: ["CMD-SHELL", "ping  -w 1 -c 1 localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
      
    